### ISSUE TITLE
API show.do Too much information

### ISSUE THREAD

**Issue by narsimplyme** [narsimplyme/PrintAnywhere#1]
문서와는 다르게 userPW까지 출력되는 문제점이 있음

    "data": {
        "user": {
            "userId": "jinmin",
            "userPw": "",
            "userName": "jinmin",
            "userMail": "jinmin@gmail.com",
            "userNickname": "jinmin",
            "userPhoneNumber": "01011111111",
            "userPoint": 1000

**Comment by leeeunkyu** [comment]
user객체에 포함된 필드값이라 아예 삭제하기는 어렵고
userPw부분에 빈 공백문자열을 넣어서 보내는걸로 변경
